### ISSUE TITLE
03-11 18:32:06.552: E/AndroidRuntime(14015): java.lang.RuntimeException: Unable to instantiate application com.firebase.androidchat.ChatApplication: java.lang.ClassNotFoundException: Didn't find class "com.firebase.androidchat.ChatApplication" on path: DexPathList[[zip file "/data/app/com.firebase.androidchat-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.firebase.androidchat-2, /vendor/lib, /system/lib]]

### ISSUE THREAD

**Issue by datomnurdin** [firebase/AndroidChat#16]
I got this error mesage when I try run your app for the first time.

```
03-11 18:32:06.552: E/AndroidRuntime(14015): FATAL EXCEPTION: main
03-11 18:32:06.552: E/AndroidRuntime(14015): java.lang.RuntimeException: Unable to instantiate application com.firebase.androidchat.ChatApplication: java.lang.ClassNotFoundException: Didn't find class "com.firebase.androidchat.ChatApplication" on path: DexPathList[[zip file "/data/app/com.firebase.androidchat-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.firebase.androidchat-2, /vendor/lib, /system/lib]]
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:509)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4450)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.ActivityThread.access$1300(ActivityThread.java:144)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.os.Looper.loop(Looper.java:137)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.ActivityThread.main(ActivityThread.java:5136)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at java.lang.reflect.Method.invoke(Method.java:525)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at dalvik.system.NativeStart.main(Native Method)
03-11 18:32:06.552: E/AndroidRuntime(14015): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.firebase.androidchat.ChatApplication" on path: DexPathList[[zip file "/data/app/com.firebase.androidchat-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.firebase.androidchat-2, /vendor/lib, /system/lib]]
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:504)
03-11 18:32:06.552: E/AndroidRuntime(14015): 	... 11 more
```

**Comment by nandha-dev** [comment]
"/AndroidChat-master/app/src/main/src" Doesn't have the java files. Instead "java" folder have those files. Delete "src" folder and Rename "java" folder to "src". It works fine
